title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

permalink: /blog/:year/:month/:day/:title/


collections:
  algorithm:
    output: true
    permalink: /:collection/:name/
  programming:
    output: true
    permalink: /:collection/:name/
  architecture:
    output: true
    permalink: /:collection/:name/
  cloud:
    output: true
    permalink: /:collection/:name/
  tutorial:
    output: true
    permalink: /:collection/:name/
  project:
    output: true

plugins:
  - jekyll-default-layout
  - jekyll-sitemap

sitemap:
  exclude: 
    - about/
    - contact/ 
  base_url: '' 